### ISSUE TITLE
Envoy tests fail locally for some people

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/chaperone#62]
<img width="1375" alt="Screenshot 2020-09-22 at 21 16 46" src="https://user-images.githubusercontent.com/16625137/93933016-ee766380-fd18-11ea-8b5e-0e0a3be2d7af.png">

**Comment by alastairong** [comment]
Full logs

[output.txt](https://github.com/Holo-Host/chaperone/files/5263859/output.txt)

**Comment by mjbrisebois** [comment]
I was able to recreate this error by setting my timeout very low.  `opened ( timeout = 1 )` in `./build/client.js`

@alastairong could you try setting that timeout higher and see if it becomes consistent?  The next thing I would check into is a port reservation

```bash
  Mock envoy
    1) should start server, create client, request, and respond

  util.sha256
    ✓ should decode SHA-256 multihash into SHA-256 digest bytes
    ✓ should encode SHA-256 digest bytes into SHA-256 multihash

  Websocket/Envoy
{ code: -32601, message: 'Method not found' }
    ✓ should fail to process request (112ms)
{ code: -32601, message: 'Method not found' }
    2) should send signed request
    ✓ should fail to send wormhole request
    ✓ should sign-up and save the assigned host (310ms)
    ✓ should sign-out
{ code: -32601, message: 'Method not found' }
    3) should sign-in and send signed request
    4) should receive and sign wormhole request
    ✓ should have no pending confirmations


  13 passing (4s)
  23 pending
  4 failing

  1) Mock envoy
       should start server, create client, request, and respond:
     TimeoutError: Waited for 0.001 seconds
      at Timeout._onTimeout (build/async_with_timeout.js:21:9)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Websocket/Envoy
       should send signed request:
     HoloError: RPC request threw error: Error type unknown: function Object() { [native code] }
      at Chaperone.<anonymous> (build/index.js:1253:31)
      at step (build/index.js:33:23)
      at Object.throw (build/index.js:14:53)
      at rejected (build/index.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Websocket/Envoy
       should sign-in and send signed request:
     HoloError: RPC request threw error: Error type unknown: function Object() { [native code] }
      at Chaperone.<anonymous> (build/index.js:1253:31)
      at step (build/index.js:33:23)
      at Object.throw (build/index.js:14:53)
      at rejected (build/index.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) Websocket/Envoy
       should receive and sign wormhole request:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/matthew/projects/chaperone/tests/unit/test_websocket.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

```
